language: python
matrix:
  include:
    - name: "Python 3.7 on Bionic Linux"
      python: 3.7
      dist: bionic
      env:
        - PIP_CMD=pip3
        - PYTHON=python3
    - name: "Python 3.7 on macOS"
      python: 3.7
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - pip3 install pytest
      env:
        - PIP_CMD=pip3
        - PYTHON=python3
    - name: "Python 3.6 on Bionic Linux"
      python: 3.6
      dist: bionic
      env:
        - PIP_CMD=pip3
        - PYTHON=python3
install:
  - $PIP_CMD install --upgrade pip
  - $PIP_CMD install -r requirements.txt
  - $PIP_CMD install .
script: $PYTHON -m pytest -v -s
