data_source: !!python/object/apply:hugin.io.FileSystemLoader
  kwds:
    data_pattern: '(?P<id>.*)\.tiff$'
    id_format: '{id}'
    type_format: 'GEE'
    input_source: /data/syno1/sage-storage/Spacenet_5/nfs/data/cosmiq/spacenet/competitions/SN5_roads/tiles_upload/train/AOI_7_Moscow/
ensemble:
  method: average # voting, weighted average
models:
  unetv14:
    #path: /home/tardis/marian/pycharm/data/terrasigna/test_terrasigna/hal720m-tardis.hdf5
#    path: /home/gabriel/Research/data/ML4EO_Paduri/models/ftr_terrasigna/hal720m-gabriel.hdf5
    path: /home/gabriel/experiments/s5/models/s5_train_test_topology_long.hdf5.hdf5
    builder: hugin.models.unet.unetv14:unet_v2
    type: keras
    window_size: [256, 256]
    stride_size: 100
    match_id: '.*'
    batch_size: 15
    swap_axes: True
    mapping:
      inputs:
        - [ "MSNone", 1 ]
        - [ "MSNone", 2 ]
        - [ "MSNone", 3 ]
        - [ "MSNone", 4 ]
      target:
        - [ "MS_GTI", 1 ]
