data_source: !!python/object/apply:hugin.io.FileSystemLoader
  kwds:
#    data_pattern: '(?P<category>[0-9A-Za-z_]+)_AOI_(?P<location>\d+_[A-Za-z0-9]+)_(?P<type>[a-zA-Z]+)_(?P<idx>[a-zA-Z0-9]+)(?P<gti>_GTI)?.tif$'
    data_pattern: '(?P<category>[0-9A-Za-z_]+)_roads_test_public_AOI_(?P<location>\d+_[A-Za-z0-9]+)_Juan_(?P<type>[a-zA-Z]+)_(?P<idx>[a-zA-Z0-9]+).tif$'
    id_format: '{location}-{idx}'
    type_format: '{type}'
    input_source: /data/syno1/sage-storage/Spacenet_5/nfs/data/cosmiq/spacenet/competitions/SN5_roads/tiles_upload/test_public/AOI_9_San_Juan/MS
#    input_source: /data/syno1/sage-storage/Spacenet_5/nfs/data/cosmiq/spacenet/competitions/SN5_roads/tiles_upload/train/AOI_7_Moscow/MS
ensemble:
  method: average # voting, weighted average
models:
  unetv14:
    #path: /home/tardis/marian/pycharm/data/terrasigna/test_terrasigna/hal720m-tardis.hdf5
#    path: /home/gabriel/Research/data/ML4EO_Paduri/models/ftr_terrasigna/hal720m-gabriel.hdf5
#    path: /home/gabriel/experiments/s5/models/s5_train_best.hdf5
    path: /home/gabriel/experiments/s5/models/s5_train_selective_all_spacenet_mine.hdf5
    builder: hugin.models.unet.unetv14:unet_v2
    type: keras
    window_size: [256, 256]
    stride_size: 100
    match_id: '.*'
    batch_size: 15
    swap_axes: True
    mapping:
      inputs:
        - [ "MS", 8 ]
        - [ "MS", 4 ]
        - [ "MS", 5 ]